[editor]
bufferline = "multiple"
idle-timeout = 50

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]

esc = ["collapse_selection", "keep_primary_selection"]


"home" = ["goto_first_nonwhitespace"]
"S-end" = "extend_to_line_end"
"S-home" = "extend_to_first_nonwhitespace"

C-d = ["scroll_down", "move_line_down"]
C-u = ["scroll_up", "move_line_up"]

[keys.insert]
"home" = ["goto_first_nonwhitespace"]


[keys.normal.space]
"[" = "add_newline_above"
"]" = "add_newline_below"
