inherits = "tokyonight"

"string" = { fg = "steel_green", modifiers = [] }
"string.special" = { fg = "steel_green", modifiers = ["italic"] }
"string.regexp" = { fg = "steel_green", modifiers = ["italic"]}

"namespace" = "teal"

"type.enum.variant" = { fg = "#D1FC9D", modifiers = ["italic"] }
"type" = { fg = "type_green", modifiers = ["bold"]}
"type.builtin" = { fg = "type_green", modifiers = ["bold"]}
"type.parameter" = { fg = "red", modifiers = ["bold"]}

# runtime/queries/rust/highlights.scm
#  primitive -> type.builtin.primitive
# ; from @type.builtin to builtin.primitive
# (primitive_type) @type.builtin.primitive
"type.builtin.primitive" = "red"

"keyword.control" = { fg = "purple" , modifiers = ["bold"]}
"keyword.storage" = { fg = "purple" , modifiers = ["bold"]}
"keyword.storage.modifier" = { fg = "purple", modifiers = []}

"constant" = "red"
"constant.builtin" = "red"

"variable.parameter" = "white"

warning = "warning"
hint = "warning"

"ui.background" = { bg = "#0a0a0d" }
"ui.virtual.inlay-hint" = "#525f88"
# "ui.statusline" = {fg = "#73DACA", bg = "#525f88"}
"ui.selection" = { fg = "lightning", bg = "#525f88", modifiers = ["italic"] }
"ui.highlight" = "#73DACA"
# "ui.highlight" = "#FF0000"
# "ui.text.focus" = "#FF0000"
# "ui.cursor.insert" = { fg = "#FF0000" }
"ui.selection.primary" = { bg = "#042326" }


[palette]
purple = "#BB9AF7"
red = "#C0768E"
lightning = "#ffcd1c"
warning = "#ff942f"
teal = "#0DB9D7"
steel_green = "#73DACA"
type_green = "#8BE9EC"
